apps:
- appName: jupyterhub
  mode: ab # ab|canary|disable
  cookieInfo:
    expiration: 48h
    canaryPercent: .90
    ifSuccessful: # if less than canaryPercent, set this cookie key/value
      key: a
      value: a
  view: # related to showing the UI elements to users (in this case, the stationary banner on datahub)
    showSuccess: true
    showFail: true
  logging:
    disable: false
port: 8080