{{- $configMap := toYaml .Values.deploymentControllerConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-controller.fullname" . }}
  labels:
  {{- include "deployment-controller.labels" . | nindent 4 }}
data:
  deployment-controller.yaml: |-
{{ tpl $configMap . | indent 4 }}