apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment-controller.fullname" . }}
  labels:
    {{- include "deployment-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deployment-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ tpl (toYaml .Values) . | sha256sum }}
      labels:
        {{- include "deployment-controller.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: config
        nfs:
          server: {{ .Values.nfs.server }}
          path: {{ .Values.nfs.path }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "deployment-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- if .Values.image.command }}
          {{- with .Values.image.command }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- else }}
          - go
          {{- end }}
          args:
          {{- if .Values.image.args }}
          {{- with .Values.image.args }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- else }}
          - run
          - ../workspaces/deployment-controller/
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /workspaces/deployment-controller/deployment-controller.yaml
            subPath: deployment-controller.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
